name: Linux Build

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: sudo apt-get -y install build-essential cmake pkg-config libglm-dev libgtkmm-3.0-dev libsigc++-2.0-dev libyaml-cpp-dev liblxi-dev texlive texlive-fonts-extra libglew-dev

    - name: Clone FFTS Repository
      run: git clone https://github.com/anthonix/ffts.git /tmp/ffts

    - name: Build FFTS Library
      shell: bash
      run: pushd /tmp/ffts && mkdir build && cd build && cmake ../ && make && sudo make install && popd

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}
      run: ls && mkdir build && cd build && cmake ../ && make
